version: '3.8'
services:
  #display_service:
  #  image: display_service        # image name
  #  build: 
  #    context: ./DisplayService   # where to find 'dockerfile'
  #    dockerfile: Dockerfile      # change if using different Dockerfile (e.g. Dockerfile-prod)
  #  environment:
  #    - VITE_APP_SERVER_URL=http://localhost
  #  ports:
  #    - 8080:8080  
  #  volumes:
  #    - ./DisplayService:/app
  #    - modules:/app/node_modules
  proxy:
    image: nginx
    volumes:
      - type: bind
        source: default.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports: 
      - 4040:4040
  user_service:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - user_service_db
      - rabbit_mq
  user_service_db:
    image: postgres:16.2
    env_file:
      - .env
    ports:
      - 5432:5432
  rabbit_mq:
    image: rabbitmq:3.13.0-management
    ports:
      - 5672:5672
      - 15672:15672
    

volumes:
  modules:
