version: '3.8'
services:
  display_service:
    image: display_service        # image name
    build: 
      context: ./DisplayService   # where to find 'dockerfile'
      dockerfile: Dockerfile      # change if using different Dockerfile (e.g. Dockerfile-prod)
    environment:
      - VITE_APP_SERVER_URL=http://localhost
    ports:
      - 8080:8080  
    volumes:
      - ./DisplayService:/app
      - pnpm_modules:/app/node_modules

volumes:
  pnpm_modules:
